### PR TITLE
chore: add react files

### PR DESCRIPTION
**Pull request by xyng**

### CODE REVIEW

**Comment by hydraVM** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **xyng**

If they are not already assigned, you can assign the PR to them by writing `/assign @xyng` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/interweberde/ching-chang-chong/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by xyng** [comment]
:star: PR built and available in a preview environment **interweberde-ching-chang-chong-pr-2** [here](http://ching-chang-chong.jx-interweberde-ching-chang-chong-pr-2.192.168.178.38.nip.io)

**Comment by hydraVM** [comment]
@xyng: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | d37df0477655ea4c590b21c36e97ab4e262d5094 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hydraVM** [comment]
@xyng: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 0f2a7f4bec93d189ab5baca0e89f309f1e987e8b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hydraVM** [comment]
@xyng: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 0f2a7f4bec93d189ab5baca0e89f309f1e987e8b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by xyng** [comment]
:star: PR built and available in a preview environment **interweberde-ching-chang-chong-pr-2** [here](http://ching-chang-chong.jx-interweberde-ching-chang-chong-pr-2.192.168.178.38.nip.io)

**Comment by xyng** [comment]
:star: PR built and available in a preview environment **interweberde-ching-chang-chong-pr-2** [here](http://ching-chang-chong.jx-interweberde-ching-chang-chong-pr-2.192.168.178.38.nip.io)

**Comment by hydraVM** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/interweberde/ching-chang-chong/pull/2#issuecomment-456466433" title="Approved">xyng</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/interweberde/ching-chang-chong/blob/master/OWNERS)~~ [xyng]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
